UICLAIM-7 Setup new UI project `ui-claims`
folio-org/ui-claims pull request #1
Opened 2024-10-28 17:28 UTC by usavkov-epam

Initial project setup

2024-10-28 17:38 UTC, BogdanDenis requested changes

2024-10-28 17:38 UTC, BogdanDenis commented on .github/workflows/build-npm-release.yml
> +# This workflow will do a clean install of node dependencies, build the source code,
Please use new shared UI workflow
Example ticket [UINOTES-151](https://folio-org.atlassian.net/browse/UINOTES-151)

2024-10-28 17:39 UTC, usavkov-epam commented
@folio-org/folio-devops cold you please check GA actions and assist with sonar?

2024-10-28 17:50 UTC, usavkov-epam commented on .github/workflows/build-npm-release.yml
> +# This workflow will do a clean install of node dependencies, build the source code,
updated

2024-10-28 17:53 UTC, BogdanDenis approved these changes

2024-10-28 21:34 UTC, julianladisch commented
> @folio-org/folio-devops could you please check GA actions and assist with sonar?

Done.

2024-10-30 06:01 UTC, usavkov-epam commented
@folio-org/acquisitions-ui please take a look

2024-10-30 13:41 UTC, alisher-epam approved these changes

2024-10-31 05:02 UTC, merged